language: python
python:
- "3.7"

install: "pip install -r requirements.txt"

script:
- python test.py

deploy:
  provider: heroku
  api_key: 
    secure: 524a3a1b-1ec0-4726-a05c-05c91b9e363b
  app: daylylyfe
  on:
    anand-anmol/Dayly-Lyfe